# Generated by Django 4.2.16 on 2025-09-01 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customdocument',
            old_name='description',
            new_name='document_description',
        ),
    ]
