# Generated by Django 5.2.1 on 2025-09-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_rename_description_customdocument_document_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdocument',
            name='file_size',
            field=models.PositiveBigIntegerField(editable=False, null=True),
        ),
    ]
