# Generated by Django 4.2.16 on 2024-09-12 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('blogpages', '0002_blogdetail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
    ]
