# Generated by Django 4.2.16 on 2024-12-05 18:04

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0005_blogdetail_body_as_streamfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='body_as_streamfield',
            field=wagtail.fields.StreamField([('text', 0), ('image', 1), ('carousel', 3)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('author', 0)]], {}), 3: ('wagtail.blocks.StreamBlock', [[('image', 1), ('quotation', 2)]], {})}, null=True),
        ),
    ]
