# Generated by Django 4.2.16 on 2025-09-01 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_customimage_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customimage',
            name='description',
        ),
    ]
